language: python

sudo: false

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "pypy"
    - "pypy3"

install: pip install .[test]

script: make ci-test

after_success:
    - codecov -X gcov
